AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda-api
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  LambdaApiTest:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaApiTest
      Role: 'arn:aws:iam::318240840298:role/Batch_execute'
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'

Outputs:
  MyFunctionUrlEndpoint:
    Description: 'My Lambda Function URL Endpoint'
    Value:
      Fn::GetAtt: LambdaApiTestUrl.FunctionUrl
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
