AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda-api
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  lambda-api-pricing:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  MyFunctionUrlEndpoint:
    Description: 'My Lambda Function URL Endpoint'
    Value:
      Fn::GetAtt: FunctionUrl.FunctionUrl
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
